import pytest
from pydantic import ValidationError
from synfinder.report import PREVIEW_DISCLAIMER, render_preview
from synfinder.schema import OutputPreview


def preview(**over):
    base = dict(format="tabular_csv", note="One row per patient.",
                preview="age,sex\n54,F\n")
    base.update(over)
    return OutputPreview(**base)


def test_preview_requires_a_note():
    with pytest.raises(ValidationError):
        preview(note="")


def test_render_puts_the_disclaimer_first():
    lines = render_preview(preview())
    assert PREVIEW_DISCLAIMER in lines[0] or PREVIEW_DISCLAIMER in lines[2]


def test_disclaimer_says_it_was_not_generated_by_the_method():
    assert "not generated by this method" in PREVIEW_DISCLAIMER.lower()


def test_render_includes_the_note_and_the_body():
    text = "\n".join(render_preview(preview()))
    assert "One row per patient." in text
    assert "age,sex" in text
