"""Export a shortlist as markdown or standalone HTML."""
from __future__ import annotations

import html as html_mod
from datetime import date

from .explain import explain
from .intake import Intake
from .ranking import Ranking
from .schema import Dataset, OutputPreview

PREVIEW_DISCLAIMER = (
    "_Illustrative of the output format — not generated by this method._"
)


def render_preview(p: OutputPreview) -> list[str]:
    """Markdown lines for a preview, disclaimer first and always."""
    return [
        "**What the output looks like**",
        "",
        PREVIEW_DISCLAIMER,
        "",
        p.note,
        "",
        "```",
        p.preview.rstrip(),
        "```",
        "",
    ]


COMPARISON_AXES = [
    "purpose", "preserves", "expertise", "scale", "maturity", "governance",
]


def comparison_rows(ranking: Ranking) -> tuple[list[str], list[list[str]]]:
    header = ["Method", "Fit"] + [
        a.replace("_", " ").title() for a in COMPARISON_AXES
    ]
    rows: list[list[str]] = []
    for c in ranking.shortlist:
        row = [c.method.name, f"{c.fit:.0%}"]
        for name in COMPARISON_AXES:
            a = c.axis(name)
            row.append("—" if a is None else f"{a.score:.2f}")
        rows.append(row)
    return header, rows


def _intake_lines(intake: Intake) -> list[str]:
    lines = [
        f"- Domain: {intake.domain}",
        f"- Data type: {intake.data_type}",
        f"- Purpose: {intake.purpose}",
        f"- Privacy requirement: {intake.privacy}",
    ]
    optional = {
        "Compute": intake.compute,
        "Expertise": intake.expertise,
        "Expected rows": intake.expected_rows,
        "Variable types": ", ".join(intake.variable_types) or None,
        "Must preserve": ", ".join(intake.preserves) or None,
        "Open licence required": intake.require_open_license,
        "Governance evidence needed": intake.needs_governance_evidence,
    }
    lines += [f"- {k}: {v}" for k, v in optional.items() if v is not None]
    return lines


def empty_result_message(
    intake: Intake, covered: bool, also_covered: list[str] | None = None
) -> str:
    """Why the shortlist is empty - an uncovered modality is not a no-match.

    `also_covered` is read from the catalog rather than hardcoded, so this
    message cannot go stale as modalities are added.
    """
    if not covered:
        have = ""
        if also_covered:
            names = sorted(d.replace("_", " ") for d in also_covered)
            have = " The catalog currently covers " + ", ".join(names) + "."
        return (
            f"SynFinder has no entries for {intake.data_type.replace('_', ' ')} "
            "data yet. That is a gap in this catalog, not a statement that no "
            f"method exists.{have}"
        )
    return (
        "No method in the catalog meets these requirements. Try relaxing the "
        "constraint shown most often in the ruled-out list below."
    )


def render_markdown(
    intake: Intake,
    ranking: Ranking,
    datasets: list[Dataset] | None = None,
    covered: bool = True,
    also_covered: list[str] | None = None,
) -> str:
    out: list[str] = [
        "# Synthetic data method recommendation",
        "",
        f"Generated by SynFinder on {date.today().isoformat()}.",
        "",
        "## What you asked for",
        "",
        *_intake_lines(intake),
        "",
        "## Recommended methods",
        "",
    ]

    if ranking.no_purpose_match and ranking.shortlist:
        out += [
            f"> **Nothing in this catalog is intended for "
            f"{intake.purpose.replace('_', ' ')} with "
            f"{intake.data_type.replace('_', ' ')} data.** The entries below "
            "are the closest available on your other constraints, but none of "
            "them is designed for what you asked. Read their caveats before "
            "going further, and treat this as a gap rather than an answer.",
            "",
        ]

    if not ranking.shortlist:
        out += [empty_result_message(intake, covered, also_covered), ""]

    for i, c in enumerate(ranking.shortlist, start=1):
        e = explain(c)
        out.append(f"### {i}. {c.method.name} — {c.fit:.0%} fit")
        out.append("")
        if e.why_fits:
            out.append("**Why it fits:** " + "; ".join(e.why_fits) + ".")
        if e.weakness:
            out.append(f"**Where it is weaker:** it {e.weakness}.")
        if e.caveats:
            out.append("**Watch out:** " + " ".join(e.caveats))
        if c.method.output_preview:
            out += render_preview(c.method.output_preview)
        if e.evaluation:
            out.append(
                "**How to check it worked:** " + "; ".join(e.evaluation) + "."
            )
        links = c.method.links
        link_bits = [
            f"[paper]({links.paper})" if links.paper else "",
            f"[code]({links.code})" if links.code else "",
            f"[docs]({links.docs})" if links.docs else "",
        ]
        link_line = " · ".join(b for b in link_bits if b)
        if link_line:
            out.append(link_line)
        out.append("")

    if ranking.shortlist:
        header, rows = comparison_rows(ranking)
        out += ["## Side by side", "",
                "| " + " | ".join(header) + " |",
                "|" + "---|" * len(header)]
        out += ["| " + " | ".join(r) + " |" for r in rows]
        out.append("")

    if datasets:
        out += ["## Ready-made synthetic datasets", ""]
        for d in datasets:
            out.append(
                f"- **{d.name}** ({d.size}, {d.license}) — {d.access_conditions}"
            )
        out.append("")

    if ranking.excluded:
        out += [
            "## Ruled out",
            "",
            f"{len(ranking.excluded)} method(s) were excluded before scoring:",
            "",
        ]
        out += [f"- **{e.method_name}** {e.reason}." for e in ranking.excluded]
        out.append("")

    return "\n".join(out)


def render_html(
    intake: Intake,
    ranking: Ranking,
    datasets: list[Dataset] | None = None,
    covered: bool = True,
    also_covered: list[str] | None = None,
) -> str:
    body = html_mod.escape(
        render_markdown(intake, ranking, datasets, covered, also_covered)
    )
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        "<title>Synthetic data method recommendation</title>"
        "<style>body{font:16px/1.6 system-ui,sans-serif;max-width:52rem;"
        "margin:2rem auto;padding:0 16px}pre{white-space:pre-wrap}</style>"
        f"</head><body><pre>{body}</pre></body></html>\n"
    )
